import SwiftUI

struct TermsOfServiceView: View {
    @Environment(\.dismiss) var dismiss
    
    var body: some View {
        NavigationView {
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    Text("Terms of Service and Assumption of Risk")
                        .font(.title)
                        .fontWeight(.bold)
                    
                    Text("**Last Updated:** March 4, 2026")
                        .foregroundColor(.secondary)
                    
                    Text("Welcome to the Climbing Wall App (\"we,\" \"our,\" or \"us\"). These Terms of Service (\"Terms\") govern your access to and use of our mobile applications, web applications, and related services (collectively, the \"Service\").")
                    
                    Text("PLEASE READ THESE TERMS CAREFULLY. THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, INCLUDING A BINDING ARBITRATION AGREEMENT, A CLASS ACTION WAIVER, AND A COMPREHENSIVE WAIVER OF LIABILITY AND ASSUMPTION OF RISK RELATED TO THE INHERENTLY DANGEROUS SPORT OF CLIMBING.")
                        .font(.subheadline)
                        .fontWeight(.bold)
                        .padding()
                        .background(Color.red.opacity(0.1))
                        .cornerRadius(8)
                        .overlay(RoundedRectangle(cornerRadius: 8).stroke(Color.red, lineWidth: 1))
                    
                    Text("By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Service.")
                    
                    Divider()
                    
                    // SECTION 1
                    Text("1. Eligibility and COPPA Compliance")
                        .font(.title2)
                        .fontWeight(.bold)
                    
                    Group {
                        Text("1.1 Age Restrictions").fontWeight(.semibold)
                        Text("You must be at least 13 years old to use the Service. If you are under 13 years of age, you are strictly prohibited from creating an account or providing any personal information.")
                        
                        Text("1.2 Minor Users (Ages 13-17)").fontWeight(.semibold)
                        Text("If you are between the ages of 13 and 17 (or the age of legal majority in your jurisdiction), you may only use the Service under the direct supervision and with the explicit consent of a parent or legal guardian who agrees to be bound by these Terms.")
                        
                        Text("1.3 Account Security").fontWeight(.semibold)
                        Text("You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use.")
                    }
                    
                    Divider()
                    
                    // SECTION 2
                    Group {
                        Text("2. Express Assumption of Risk and Waiver of Liability")
                            .font(.title2)
                            .fontWeight(.bold)
                        
                        Text("2.1 Inherently Dangerous Activity").fontWeight(.semibold)
                        Text("Rock climbing, bouldering, training, and utilizing user-generated routing or beta videos (\"Climbing Activities\") are inherently dangerous activities. These activities involve significant risks, including but not limited to, the risk of severe property damage, bodily injury, permanent disability, paralysis, and death.")
                        
                        Text("2.2 Acknowledgment of Risk").fontWeight(.semibold)
                        Text("By using the Service, you expressly acknowledge and agree that:\n(a) You voluntarily choose to participate in Climbing Activities.\n(b) The routes, grades, beta videos, AI hold detections, and user instructions (\"Climbing Content\") provided on the Service are generated by third-party users and/or automated systems and are provided for informational and entertainment purposes **ONLY**.\n(c) We do not verify the safety, stability, or accuracy of any Climbing Content, including custom routes, holds, or the physical integrity of the walls depicted.")
                        
                        Text("2.3 Complete Waiver and Release").fontWeight(.semibold)
                        Text("To the maximum extent permitted by applicable law, you hereby irrevocably release, waive, discharge, and covenant not to sue the Climbing Wall App, its developers, operators, affiliates, officers, directors, employees, and agents (the \"Released Parties\") from any and all liability, claims, demands, actions, or rights of action, which are related to, arise out of, or are in any way connected with your participation in Climbing Activities or your reliance on any Climbing Content found on the Service.")
                    }
                    
                    Divider()
                    
                    // SECTION 3
                    Group {
                        Text("3. User-Generated Content (UGC)")
                            .font(.title2)
                            .fontWeight(.bold)
                        Text("The Service permits users to upload, post, and share content, including but not limited to custom routes, beta videos, photos of walls, markings, text comments, and grade votes (\"UGC\").")
                        
                        Text("3.1 License Grant").fontWeight(.semibold)
                        Text("By posting UGC, you grant us a worldwide, non-exclusive, royalty-free, transferable, sublicensable license to use, reproduce, distribute, prepare derivative works of, and display your UGC in connection with operating and providing the Service.")
                        
                        Text("3.2 Your Responsibilities").fontWeight(.semibold)
                        Text("You represent and warrant that:\n- You own or have the necessary licenses, rights, and permissions to publish the UGC.\n- Your UGC does not infringe on the intellectual property rights, privacy rights, or publicity rights of any third party.\n- Your UGC does not contain malicious code, AI manipulation designed to deceive safety protocols, or explicit/illegal material.")
                        
                        Text("3.3 Content Moderation and Removal").fontWeight(.semibold)
                        Text("We act solely as a passive conduit for your online distribution and publication of UGC. However, we reserve the right (but have no obligation) to review, monitor, flag, filter, modify, refuse, or remove any or all UGC from the Service at our sole discretion, without notice, particularly if such content violates these Terms or poses a threat to user safety.")
                        
                        Text("3.4 DMCA Copyright Policy").fontWeight(.semibold)
                        Text("We respect the intellectual property rights of others. We will respond promptly to valid notices of alleged copyright infringement that comply with the Digital Millennium Copyright Act (\"DMCA\").")
                    }
                    
                    Divider()
                    
                    // SECTION 4
                    Group {
                        Text("4. Artificial Intelligence & Automated Tools")
                            .font(.title2)
                            .fontWeight(.bold)
                        
                        Text("4.1 AI Hold Detection").fontWeight(.semibold)
                        Text("The Service may utilize artificial intelligence (\"AI\") to auto-detect holds, parse photos, or suggest routing. You acknowledge that AI technologies are experimental and prone to errors. You must independently verify the physical reality, safety, and stability of any hold or route before attempting to climb it.")
                        
                        Text("4.2 Disclaimer of AI Reliability").fontWeight(.semibold)
                        Text("The Released Parties bear no liability for injuries sustained resulting from reliance on AI-generated routing, hold selection, or beta generation.")
                    }
                    
                    Divider()
                    
                    // SECTION 5 & 6
                    Group {
                        Text("5. Indemnification")
                            .font(.title2)
                            .fontWeight(.bold)
                        Text("You agree to defend, indemnify, and hold harmless the Released Parties from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from:\n(a) Your use of and access to the Service;\n(b) Your violation of any term of these Terms;\n(c) Your violation of any third-party right, including without limitation any copyright, property, or privacy right; or\n(d) Any claim that your UGC caused damage to a third party (including physical injury).")
                        
                        Text("6. Disclaimers and Limitations of Liability")
                            .font(.title2)
                            .fontWeight(.bold)
                            .padding(.top, 10)
                        
                        Text("6.1 \"As Is\" Basis").fontWeight(.semibold)
                        Text("THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.")
                            .font(.caption)
                            .textCase(.uppercase)
                        
                        Text("6.2 Limitation of Liability").fontWeight(.semibold)
                        Text("IN NO EVENT SHALL THE RELEASED PARTIES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT DAMAGES ARISING FROM YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\nNOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US FOR THE SERVICE DURING THE THREE (3) MONTHS PRIOR TO THE EVENT GIVING RISE TO LIABILITY.")
                            .font(.caption)
                            .textCase(.uppercase)
                    }
                    
                    Divider()
                    
                    // SECTION 7 & 8
                    Group {
                        Text("7. Governing Law and Dispute Resolution")
                            .font(.title2)
                            .fontWeight(.bold)
                        
                        Text("7.1 Governing Law").fontWeight(.semibold)
                        Text("These Terms shall be governed by the laws of the State of Delaware, USA, without respect to its conflict of laws principles.")
                        
                        Text("7.2 Binding Arbitration").fontWeight(.semibold)
                        Text("Any dispute, claim, or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation, or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by binding arbitration rather than in court.")
                        
                        Text("7.3 Class Action Waiver").fontWeight(.semibold)
                        Text("YOU AND WE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR OUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.")
                            .font(.caption)
                            .textCase(.uppercase)
                        
                        Text("8. Modifications to the Terms")
                            .font(.title2)
                            .fontWeight(.bold)
                            .padding(.top, 10)
                        
                        Text("We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.")
                    }
                    
                    Text("For any questions regarding these Terms, please contact legal@climbapp.local.")
                        .font(.footnote)
                        .italic()
                        .foregroundColor(.secondary)
                        .padding(.top, 20)
                        .padding(.bottom, 40)
                    
                }
                .padding()
            }
            .navigationTitle("Terms of Service")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .fontWeight(.bold)
                }
            }
        }
    }
}

struct TermsOfServiceView_Previews: PreviewProvider {
    static var previews: some View {
        TermsOfServiceView()
    }
}
